name: Bitbucket Sync
description: Syncs the repository into bitbucket
branding:
  icon: check-circle
  color: green
runs:
  using: docker
  image: Dockerfile
inputs:
  repository:
    description: The Repository URI
    required: true
  client_key:
    required: true
  client_secret:
    required: true
